theme = "tabi"
base_url = "https://shaozk.github.io/"
title = "Home"

taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
]

[markdown.highlighting]
theme = "catppuccin-frappe"
style = "class"


